# Generated by Django 5.0.6 on 2024-06-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0010_alter_carousel_action_name_alter_carousel_sub_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='action_name',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
    ]
